apiVersion: v1
kind: Service
metadata:
  name: qv2ray
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "qv2ray"
    port: 8080
  selector:
    app: v2rayn
